# Site settings
title: Brandon Fox
email: bl.fox@live.com
description: > # this means to ignore newlines until "baseurl:"
  The personal site for Brandon Fox.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  bradndon

# Build settings
markdown: kramdown
